set_property PACKAGE_PIN Y9 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property PACKAGE_PIN U10 [get_ports oled_data_comm]
set_property IOSTANDARD LVCMOS18 [get_ports oled_data_comm]
set_property PACKAGE_PIN U9 [get_ports oled_resetn]
set_property IOSTANDARD LVCMOS18 [get_ports oled_resetn]
set_property PACKAGE_PIN AB12 [get_ports oled_sclock]
set_property IOSTANDARD LVCMOS18 [get_ports oled_sclock]
set_property PACKAGE_PIN AA12 [get_ports oled_sdata]
set_property IOSTANDARD LVCMOS18 [get_ports oled_sdata]
set_property PACKAGE_PIN U11 [get_ports oled_vbat]
set_property IOSTANDARD LVCMOS18 [get_ports oled_vbat]
set_property PACKAGE_PIN U12 [get_ports oled_vdd]
set_property IOSTANDARD LVCMOS18 [get_ports oled_vdd]
set_property PACKAGE_PIN P16 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

create_clock -period 10.000 -name clock -waveform {0.000 5.000} [get_ports clock]
create_generated_clock -name spi_control_inst1/sclock -source [get_ports clock] -divide_by 10 [get_pins spi_control_inst1/sclock_reg/Q]
